version: '3.8'
services:
  root-config:
    build: 
      context: ./root-html-file
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./root-config:/app/root
    command: npm run serve
    environment:
      NODE_ENV: development
  about:
    build: 
      context: ./about
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./about:/app/about
    command: npm run serve --port 9001
    environment:
      - NODE_ENV=development
  sidenav:
    build: 
      context: ./sidenav
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    volumes:
      - ./sidenav:/app/sidenav
    command: npm run serve --port 9002
    environment:
      - NODE_ENV=development
  todo:
    build: 
      context: ./todo
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./todo:/app/todo
    command: npm run serve --port 9003
    environment:
      - NODE_ENV=development